// tokens/tokens.json (+ tokens/themes/*.json, tokens/brands/*.json) → src/css/tokens.css, src/tokens.ts
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { checkMode, finish, output } from "./lib/output.mjs";
import { DENSITIES, loadTokens } from "./lib/tokens.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { tokens, resolve, toCss, rawIn, valueIn, themes, brands } = loadTokens(root);
const extraThemes = themes.filter((t) => t.name !== t.base);

const decl = (t, v) => `  ${t.cssVar}: ${v};`;
const indent = (s) => s.replace(/^/gm, "  ");
const HEADER = "/* GENERATED by scripts/build-tokens.mjs from tokens/ — do not edit by hand. */";

const staticTokens = tokens.filter((t) => t.light === undefined && t.css === undefined);
const themed = tokens.filter((t) => t.light !== undefined && t.css === undefined);
const derived = tokens.filter((t) => t.css !== undefined);
const dense = tokens.filter((t) => t.density !== undefined);

const densityBlock = (mode) =>
  dense.map((t) => decl(t, toCss(mode === "compact" ? t.value : t.density[mode], t.type))).join("\n");
const darkBlock = themed.map((t) => decl(t, toCss(t.value, t.type))).join("\n");
const lightBlock = themed.map((t) => decl(t, toCss(t.light, t.type))).join("\n");

const css = `${HEADER}

/* Theme-independent tokens. Density-aware ones hold their compact value here. */
:root {
${staticTokens.map((t) => decl(t, toCss(t.value, t.type))).join("\n")}
}

/* Dark: the default, or forced with data-theme="dark" / .dark on any element */
:root,
[data-theme="dark"],
.dark {
  color-scheme: dark;
${darkBlock}
}

/* Light via OS preference, unless a theme is forced */
@media (prefers-color-scheme: light) {
  :root:not([data-theme]):not(.dark) {
    color-scheme: light;
${indent(lightBlock)}
  }
}

/* Light, forced on any element */
[data-theme="light"],
.light {
  color-scheme: light;
${lightBlock}
}
${extraThemes
  .map(
    (theme) => `
/* ${theme.name}, built on ${theme.base}. ${theme.description ?? ""} */
[data-theme="${theme.name}"] {
  color-scheme: ${theme.base};
${themed.map((t) => decl(t, toCss(rawIn(t, theme.name), t.type))).join("\n")}
}
`,
  )
  .join("")}
/* Derived from the themed tokens above. Redeclared on every theme and brand root so nested ones recompute. */
:root,
[data-theme],
[data-brand],
.dark,
.light {
${derived.map((t) => decl(t, t.css)).join("\n")}
}

/* Density: compact is the default. Touch screens get "touch" automatically; data-density forces a mode on any element. */
@media (pointer: coarse) {
  :root:not([data-density]) {
${indent(densityBlock("touch"))}
  }
}
${DENSITIES.map((mode) => `\n[data-density="${mode}"] {\n${densityBlock(mode)}\n}`).join("\n")}
`;

output(join(root, "src/css/tokens.css"), css);

// ---- TypeScript ----
const tsEntries = tokens
  .map((t) => {
    const fields = [
      `cssVar: ${JSON.stringify(t.cssVar)}`,
      `type: ${JSON.stringify(t.type)}`,
      `value: ${JSON.stringify(resolve(t.value))}`,
    ];
    if (t.light !== undefined) fields.push(`light: ${JSON.stringify(resolve(t.light))}`);
    if (t.light !== undefined && t.css === undefined && extraThemes.length) {
      fields.push(`themes: ${JSON.stringify(Object.fromEntries(extraThemes.map((th) => [th.name, valueIn(t, th.name)])))}`);
    }
    if (t.category) fields.push(`category: ${JSON.stringify(t.category)}`);
    if (t.density !== undefined) fields.push(`density: ${JSON.stringify(t.density)}`);
    if (t.description) fields.push(`description: ${JSON.stringify(t.description)}`);
    return `  ${JSON.stringify(t.name)}: { ${fields.join(", ")} },`;
  })
  .join("\n");

const ts = `// GENERATED by scripts/build-tokens.mjs from tokens/ — do not edit by hand.

export interface TokenDefinition {
  /** CSS custom property, e.g. "--ayy-color-bg". */
  readonly cssVar: string;
  readonly type: string;
  /** Dark-theme (default) value, references resolved. For density-aware tokens: the compact value. */
  readonly value: string | number | readonly (string | number)[];
  /** Light-theme value, for themed tokens. */
  readonly light?: string;
  /** Values in the other themes (dark-contrast, light-gray…), for themed tokens. */
  readonly themes?: Readonly<Record<string, string>>;
  /** Grouping for docs, e.g. "Surfaces", "Text", "Status" (colour tokens). */
  readonly category?: string;
  /** Values for the other densities, for density-aware tokens. */
  readonly density?: { readonly comfortable: string; readonly touch: string };
  readonly description?: string;
}

export const tokens = {
${tsEntries}
} as const satisfies Record<string, TokenDefinition>;

export type TokenName = keyof typeof tokens;

/** Themes for data-theme / setTheme(). Each extra theme builds on "dark" or "light" and starts with its name. */
export const themes = ${JSON.stringify(themes.map((t) => t.name))} as const;
export type ThemeName = (typeof themes)[number];

/** The base colour scheme of each theme. */
export const themeBase = ${JSON.stringify(Object.fromEntries(themes.map((t) => [t.name, t.base])))} as const satisfies Record<ThemeName, "dark" | "light">;

/** Brands shipped as ayywi/brands/<name>.css (from tokens/brands/). */
export const brands = ${JSON.stringify(brands.map((b) => b.name))} as const;
export type BrandName = (typeof brands)[number];

/** What each shipped brand is made from: pass one to createBrand() or setBrand() to apply it without its stylesheet. */
export const brandPresets = {
${brands.map((b) => `  ${JSON.stringify(b.name)}: ${JSON.stringify(b.input)},`).join("\n")}
} as const;
`;

output(join(root, "src/tokens.ts"), ts);
finish("tokens");
if (!checkMode) {
  console.log(
    `tokens: ${tokens.length} (${staticTokens.length} static, ${themed.length} themed, ${derived.length} derived, ${dense.length} density-aware); themes: ${themes.map((t) => t.name).join(", ")}; brands: ${brands.map((b) => b.name).join(", ") || "none"}`,
  );
}
